# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "centos" do |app|
    app.vm.box = "bento/centos-7.4"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "./test.yml"
    end
  end
end
